# build stage
FROM golang:1.24-bullseye AS builder

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o app ./main.go

# production stage
FROM debian:bullseye-slim



# Install LibreOffice + deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    libreoffice-core \
    libreoffice-writer \
    libreoffice-common \
    fonts-dejavu \
    fontconfig \
    ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy Calibri fonts (pastikan ada di folder fonts/)
COPY fonts/*.ttf /usr/share/fonts/truetype/msttcorefonts/
COPY fonts /root/fonts
RUN fc-cache -f -v

WORKDIR /root/
COPY --from=builder /app/app .
COPY --from=builder /app/templates ./templates

CMD ["./app"]
EXPOSE 8083
