// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "backend-brevet/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IUserSessionRepository is an autogenerated mock type for the IUserSessionRepository type
type IUserSessionRepository struct {
	mock.Mock
}

// GetByRefreshToken provides a mock function with given fields: ctx, token
func (_m *IUserSessionRepository) GetByRefreshToken(ctx context.Context, token string) (*models.UserSession, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetByRefreshToken")
	}

	var r0 *models.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.UserSession, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.UserSession); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, session
func (_m *IUserSessionRepository) Update(ctx context.Context, session *models.UserSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIUserSessionRepository creates a new instance of IUserSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserSessionRepository {
	mock := &IUserSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
